load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "relay",
    srcs = [
        "relay.go",
        "ws.go",
    ],
    importpath = "raptormark/internal/relay",
    visibility = ["//:__subpackages__"],
)

go_test(
    name = "relay_test",
    srcs = ["relay_test.go"],
    embed = [":relay"],
)
