package builder

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// LinkAll is the final ecvisor link, run inside the builder image: compile the
// generated registry.c and link it with the N namespaced lifted objects and
// libecvisor.a into one WASI module.
//
// The registry.c (generated by internal/link) defines `ecv_programs[]` /
// `ecv_program_count` / `ecv_program_size`, binding each program's renamed
// `_ecv<TAG>_*` symbols to the ecvisor runtime's EcvProgram descriptors.
type LinkAll struct {
	Registry string `name:"registry" required:"" type:"path" help:"Generated registry.c from internal/link."`
	Out      string `name:"out" required:"" type:"path" help:"WASI module to write."`
	// Space-separated rather than repeated, because that is the surface
	// internal/translate.Link builds and the scripts accepted.
	Objs string `name:"objs" required:"" help:"Space-separated lifted objects."`
	// Must match how the objects were TRANSLATED. It is the module's own record
	// of that, and ecvisor refuses the runtime gate without it — see
	// markerC below.
	InlineCallHistory bool `name:"inline-call-history" help:"Record that these objects were lifted with --inline-call-history, which is what permits RAPTORMARK_ECV_INLINE_CH=1 to take effect."`
	// ADDITIVE, not an alternative. See sideLink below.
	SideOut string `name:"side-out" type:"path" help:"Also emit one PIC side module per program into this directory, for an embedder that instantiates modules separately. The flat module is still produced."`
	// Selects WHICH libecvisor.a to link, which selects the network backend and
	// therefore the module's import surface. See ecvisorArchive.
	Profile string `name:"profile" default:"wasmedge" enum:"wasmedge,loopback,browser" help:"Runtime profile: 'wasmedge' (default) links the WasmEdge socket backend; 'loopback' links the pure-Rust in-process one and imports no socket function at all; 'browser' links the raptormark_net_v1 backend, whose wait never blocks."`
}

// ecvisorArchive resolves a profile to the staticlib the image built for it.
//
// The profile is a LINK-time choice because the backend is a compile-time one:
// `runtime/src/net` selects its backend with `cfg`, not with a trait object,
// precisely so an unused backend's imports never enter the module. Two archives
// is the cost of that guarantee, and the builder image builds both.
//
// ⚠️ `wasmedge` must keep resolving to the bare `/opt/ecvisor/libecvisor.a`.
// That path is what every existing artifact linked against, and
// `TestLinkArgsMatchTheScript` asserts the default argv verbatim.
func ecvisorArchive(profile string) string {
	switch profile {
	case "loopback":
		return "/opt/ecvisor/loopback/libecvisor.a"
	case "browser":
		return "/opt/ecvisor/browser/libecvisor.a"
	}
	return "/opt/ecvisor/libecvisor.a"
}

// markerC is the strong `__ecv_ch_built = 1` that opts a module into the
// inlined call history at RUN time.
//
// The shim (runtime/cshim/ecv_globals.c) defines a WEAK zero, so a module linked
// without this keeps zero and ecvisor refuses to enable the fast path no matter
// what the environment says. A strong definition wins over a weak one, and an
// absent strong definition is not an undefined symbol — so the default link is
// unchanged and cannot fail at instantiation.
//
// It is a whole translation unit rather than a linker flag because wasm-ld has
// no `--defsym` for data, and it belongs at LINK time rather than in any single
// object because there is exactly one module and N lifted objects.
const markerC = `/* Generated by link-all. Do not edit. */
int __ecv_ch_built = 1;
`

func (c *LinkAll) Run() error {
	objs := strings.Fields(c.Objs)
	if len(objs) == 0 {
		return usageErrorf("--objs is empty")
	}

	sourceLoginProfile()
	sdk, err := wasiSDK()
	if err != nil {
		return err
	}
	clang := sdk + "/bin/clang"
	sysroot := "--sysroot=" + sdk + "/share/wasi-sysroot"

	regObj := filepath.Join(filepath.Dir(c.Registry), "registry.o")
	if err := run(clang, "-O3", sysroot, "-c", c.Registry, "-o", regObj); err != nil {
		return err
	}

	// The build marker, when these objects were lifted for it. Compiled beside
	// the registry so the module carries its own record of how it was built.
	var extra []string
	if c.InlineCallHistory {
		markerSrc := filepath.Join(filepath.Dir(c.Registry), "ecv_ch_built.c")
		if err := os.WriteFile(markerSrc, []byte(markerC), 0o644); err != nil {
			return err
		}
		markerObj := filepath.Join(filepath.Dir(c.Registry), "ecv_ch_built.o")
		if err := run(clang, "-O2", sysroot, "-c", markerSrc, "-o", markerObj); err != nil {
			return err
		}
		extra = append(extra, markerObj)
	}

	pre := c.Out + ".pre"
	archive := ecvisorArchive(c.Profile)
	// The re-entrant surface goes only on non-default profiles. Adding four
	// exports to the shipping module would change nothing a host can observe,
	// but it would change the artifact and the verbatim arg test for no reason:
	// nothing drives them there, because a blocking backend never goes idle.
	if c.Profile != "wasmedge" {
		surface := ReentrantSurface
		if c.Profile == "browser" {
			// Only the browser backend keeps a readiness cache for the host to
			// push into; the others discover readiness themselves.
			// `ecv_signal` rides with the browser profile for the same reason:
			// a guest in a tab has no outside process that could `kill` it, so
			// without this a supervisor can only ever be watched starting up.
			surface = append(append([]string{}, surface...), "ecv_net_ready", "ecv_signal")
		}
		extra = append(extra, exportFlags(surface)...)
	}
	if err := run(clang, linkArgs(sysroot, objs, regObj, pre, archive, extra...)...); err != nil {
		return err
	}

	if err := c.finalise(pre); err != nil {
		return err
	}

	names := ""
	if wasmOptNames() {
		names = ", named"
	}
	if !wasmOptEnabled() {
		names += ", unoptimised"
	}
	fmt.Printf("link-all: built %s (%d programs, no-proposal wasm%s)\n", c.Out, len(objs), names)

	if c.SideOut != "" {
		if err := c.sideLink(clang, sdk, sysroot, objs); err != nil {
			return err
		}
	}
	return nil
}

// sideLink emits one PIC side module per program, from the SAME objects the flat
// module above was linked from.
//
// # Why this is additive rather than a mode
//
// The two end states of MULTIMODULE.md §5 are not exclusive: one set of
// translated objects serves both, because every object is compiled `-fPIC`
// (see compileIR) and a PIC object links flat with an unchanged import surface.
// Translation is the expensive half of the pipeline; a second LINK is about a
// second. So both artifacts come out of one invocation, and the stock-shim
// module is not affected by asking for the other.
//
// # What a side module is here
//
// One program, exporting exactly its `ecv_program_<i>` descriptor -- the single
// symbol `internalize` already preserves -- and importing everything else:
// `__memory_base`, `__table_base`, and the supervisor's `_ecv_*` intrinsics.
// The supervisor is NOT linked in; that is what makes it a side module, and
// supplying it is the embedder's job.
//
// ⚠️ EXPLICIT `--export`, never `--export-all`. `wasm-ld --experimental-pic
// -shared --export-all` CRASHES on a real lifted object (wasi-sdk 24, LLVM crash
// report). The same link with one explicit export succeeds. Exporting exactly
// the descriptor is what we want anyway, so the workaround costs nothing -- but
// anything that later wants a program's whole surface will meet the crash.
//
// ⚠️ Nothing on the SHIPPING path instantiates more than one module (§4). The
// artifacts are nonetheless runnable: `e2e/testdata/embedder.mjs` drives the §8
// sequence over them under node, which is a development harness and not a
// deployment target. Building both here is what keeps the two paths from
// drifting.
//
// The supervisor is emitted alongside, into the same directory. A side module
// without the module that satisfies its imports is not a deliverable, and while
// the supervisor link lived only in JOURNAL.md as a clang command nobody could
// run the pair without retyping it.
func (c *LinkAll) sideLink(clang, sdk, sysroot string, objs []string) error {
	if err := os.MkdirAll(c.SideOut, 0o755); err != nil {
		return err
	}
	// Asked for rather than hardcoded: the path embeds a clang major version
	// (.../lib/clang/18/...) that moves with the wasi-sdk.
	bi, err := output(clang, "--target=wasm32-wasi", "--print-libgcc-file-name", "--rtlib=compiler-rt")
	if err != nil {
		return fmt.Errorf("locating compiler-rt for the side link: %w", err)
	}
	libc := filepath.Join(sdk, "share/wasi-sysroot/lib/wasm32-wasip1/libc.a")
	for i, obj := range objs {
		base := strings.TrimSuffix(filepath.Base(obj), ".o")
		out := filepath.Join(c.SideOut, base+".side.wasm")
		if err := run(clang, sideLinkArgs(sysroot, obj, out, i, strings.TrimSpace(bi), libc)...); err != nil {
			return fmt.Errorf("side link of %s: %w", base, err)
		}
	}
	sup := filepath.Join(c.SideOut, "supervisor.wasm")
	if err := run(clang, supervisorLinkArgs(sysroot, sup)...); err != nil {
		return fmt.Errorf("supervisor link: %w", err)
	}
	fmt.Printf("link-all: built %d side module(s) and %s in %s\n",
		len(objs), filepath.Base(sup), c.SideOut)
	return nil
}

// SupervisorSurface is what a side module imports from `env` and the supervisor
// must therefore export: the lifter's intrinsics and the two globals the lifted
// code reads inline.
//
// It is exported from this package so the e2e side-module test can assert
// against the list the LINKER uses rather than against a second copy of it. Two
// hand-maintained lists of the same contract is how a contract drifts.
//
// ⚠️ `__ecv_unwinding` and `__stack_pointer` are wasm GLOBALS, not functions.
// `__ecv_unwinding` comes from `runtime/cshim/ecv_globals.c` (elfconv patch 0059
// made the suspend check a global read instead of an `_ecv_suspended` call);
// `__stack_pointer` is wasm-ld's own shadow-stack global, and exporting it is
// what lets every module share ONE shadow stack.
var SupervisorSurface = []string{
	"_ecv_func_epilogue",
	"_ecv_get_indirectbr_block_address",
	"_ecv_save_call_history",
	"_ecv_unreached",
	"__ecv_unwinding",
	"__ecv_warning",
	"__remill_barrier_load_store",
	"__remill_barrier_store_store",
	"__remill_error",
	"__remill_flag_computation_overflow",
	"__remill_function_call",
	"__remill_function_return",
	"__remill_jump",
	"__remill_missing_block",
	"__remill_syscall_tranpoline_call",
}

// SupervisorControl is what the EMBEDDER calls, as opposed to what a side module
// imports. Neither is reachable from lifted code.
//
// `ecv_reserve_side` is the one that is easy to think unnecessary. It exists
// because the two obvious ways to place a side module's memory are both silent
// corruption: `memory.grow` from the embedder takes a region wasi-libc's
// dlmalloc never saw and can later hand out again, and `__heap_base` is where
// the 384 MiB arena itself comes from. See MULTIMODULE.md §8.
var SupervisorControl = []string{"ecv_register_program", "ecv_reserve_side"}

// supervisorLinkArgs links ecvisor as a standalone module: the same objects the
// flat link ends with, minus the lifted programs and the registry.
//
// # Why there is no registry.o here
//
// That is the whole point of the shape. With no `registry.c`, `ecv_programs`,
// `ecv_program_count` and `ecv_program_size` are undefined and `--allow-undefined`
// resolves them to ZERO -- which `abi::registry()` reads as "no programs yet"
// and the embedder then fixes by calling `ecv_register_program` per side module.
//
// ⚠️ That zero once produced `EcvProgram ABI mismatch: C 0 vs Rust 72 bytes`,
// a diagnostic pointing at struct layout, which was the one thing not wrong.
//
// # --growable-table
//
// Step 4 of the §8 sequence grows the table to make room for each side module's
// entries. wasm-ld gives the exported table a MAXIMUM equal to its initial size
// unless this is passed, and `WebAssembly.Table.prototype.grow` past a maximum
// throws -- so without it the embedder can place exactly zero side modules.
func supervisorLinkArgs(sysroot, out string) []string {
	args := []string{
		"-O3", sysroot,
		"-Wl,--allow-undefined",
		"-Wl,-z,stack-size=16777216",
		"-Wl,--export-table", "-Wl,--growable-table",
	}
	for _, sym := range SupervisorSurface {
		args = append(args, "-Wl,--export="+sym)
	}
	for _, sym := range SupervisorControl {
		args = append(args, "-Wl,--export="+sym)
	}
	// The shadow stack, shared by every module in the instance.
	args = append(args, "-Wl,--export=__stack_pointer")
	return append(args, "-o", out,
		"/opt/ecvisor/ecv_sp.o", "/opt/ecvisor/ecv_globals.o", "/opt/ecvisor/libecvisor.a")
}

// sideLinkArgs is the per-program PIC side-module link. Split out so the flags
// can be asserted without a toolchain; TestSideLinkNeverExportsAll holds the
// `--export-all` prohibition above.
// The two archives are named LAST and by path, and both choices are measured.
//
// A side module otherwise imports `__multi3` and `fabs`, which the supervisor
// does not export -- and widening the boundary for them would be the wrong
// trade: `fabs` is a single wasm instruction (`f64.abs`), so importing it makes
// a cross-module call out of one opcode, which is exactly the inlining loss
// MULTIMODULE.md §6 identifies, at the worst possible granularity. Linking them
// locally costs **+5,371 bytes per side module (+0.17%)**, measured on a real
// program object, and leaves the import surface at exactly the contract.
//
// Archives are lazy, so naming them pulls only the members that resolve
// something -- `math-builtins.o` is 3,132 bytes of libc.a's several MB.
//
// ⚠️ `-lc` does NOT work here: it resolves to a libc variant with no `fabs`,
// and the link then succeeds while still importing it. The wasip1 archive is
// named explicitly because wasip1 is what this pipeline targets.
func sideLinkArgs(sysroot, obj, out string, index int, builtins, libc string) []string {
	return []string{
		"-O3", sysroot, "-fPIC", "-nostdlib",
		"-Wl,--experimental-pic", "-Wl,-shared", "-Wl,--allow-undefined",
		"-Wl,--export=" + fmt.Sprintf("ecv_program_%d", index),
		"-o", out, obj, libc, builtins,
	}
}

// linkArgs is the module link.
//
// -z stack-size: enlarge the wasm shadow stack to hold entry.rs's per-guest
// stack gap (GUEST_STACK_GAP, 512 KiB) plus deep guest recursion. The default
// (64 KiB) is far too small once the scheduler reserves the gap. 16 MiB gives
// ample headroom. --allow-undefined stays as transitional link-slack.
//
// The two C shims carry what Rust cannot state at the wasm level, so they are
// separate objects rather than members of libecvisor.a:
//
//	ecv_sp.o       the shadow-stack-pointer probe (wasm inline asm)
//	ecv_globals.o  the wasm globals the LIFTED code reads inline —
//	               `__ecv_unwinding`, which replaces the `_ecv_suspended` call
//	               after every guest call and syscall (elfconv patch 0059)
//
// Both must precede libecvisor.a, like the lifted objects: wasm-ld resolves an
// archive against the undefined symbols it has already seen, and libecvisor.a
// references the ecv_globals.o accessors.
//
// The yield-unwind shim (ecv_sjlj.o, ecv_sjlj_helpers.o, -lsetjmp) is gone:
// suspending is a plain return now, so nothing needs setjmp/longjmp. See
// runtime/src/intrinsics.rs and elfconv patch 0026.
// ReentrantSurface is the host interface a re-entrant embedder drives instead
// of `_start`: boot once, then ask for slices.
//
// ⚠️ THESE MUST BE EXPORTED EXPLICITLY OR THEY ARE NOT LINKED AT ALL. They live
// in libecvisor.a and nothing inside the module references them, and wasm-ld
// never pulls an unreferenced member out of an archive -- so without
// `--export=` they are not merely un-exported, they are absent. That is the
// same mechanism that made a neutralization silently fail to fire during the
// loopback work, and it is worth stating twice.
//
// `--export-all` is NOT the shortcut: it crashes wasm-ld on a real lifted object
// (see sideLinkArgs below).
var ReentrantSurface = []string{
	"ecv_boot",
	"ecv_run_slice",
	"ecv_next_deadline_in_ms",
	"ecv_exit_code",
}

func linkArgs(sysroot string, objs []string, regObj, out, archive string, extra ...string) []string {
	args := []string{"-O3", sysroot, "-Wl,--allow-undefined", "-Wl,-z,stack-size=16777216", "-o", out}
	args = append(args, objs...)
	args = append(args, regObj)
	// Before the shims: `ecv_ch_built.o` carries the STRONG `__ecv_ch_built`
	// that overrides ecv_globals.o's weak zero.
	args = append(args, extra...)
	// The two C shims are profile-independent: they state wasm-level facts
	// (the shadow-stack probe, the `__ecv_unwinding` global), not host ones.
	return append(args,
		"/opt/ecvisor/ecv_sp.o", "/opt/ecvisor/ecv_globals.o", archive)
}

// exportFlags renders `--export=` linker flags, or nothing at all.
//
// Nothing is the DEFAULT and it matters: the shipping profile's argv has to stay
// byte-identical, because `TestLinkArgsMatchTheScript` asserts it verbatim and
// every existing artifact was produced by it.
func exportFlags(syms []string) []string {
	out := make([]string, 0, len(syms))
	for _, s := range syms {
		out = append(out, "-Wl,--export="+s)
	}
	return out
}

// finalise consumes the pre-module: it runs wasm-opt over it and removes it, or
// — with ECV_WASM_OPT=0 — renames it into place unchanged. Either way `pre` does
// not survive the call.
//
// wasm-opt lowers nothing here. Three mechanisms held this slot in turn, each
// getting from a deep blocking syscall back to the scheduler:
//
//	--asyncify              mutually exclusive with elflift's --fork_emulation
//	                        call_indirect returns (traps entering unwind state)
//	--translate-to-exnref   rewrote the SjLj shim's LEGACY EH to standard exnref
//	(nothing)               suspension is a plain return; see elfconv patch 0026
//
// The third is not a cheaper spelling of the other two. The full-replay
// scheduler rebuilds every suspended process by call-history replay, so the
// abandoned frames are discarded either way — a return preserves exactly as much
// as an unwind did, which is nothing. Dropping the unwind dropped the last wasm
// proposal out of the emitted module, and that is what lets a stock released
// runwasi shim run it (e2e/containerd_test.go). Do not put a proposal back
// without re-checking that test; TestWasmOptEnablesNoProposal guards the flags.
//
// ECV_WASM_OPT=0 SKIPS the pass entirely, for the relink-heavy loop where a
// runtime-only change reuses every translated object and the final link is the
// whole cycle. It is not free, and the number is not the one this comment used
// to imply. Measured 2026-08-15 on the cached openssl object (149 MB) in the
// builder image:
//
//	wasm-ld link (149 MB object + registry.o + libecvisor.a)    1 s
//	wasm-opt -g -O0 round trip                                 52 s
//	                             127,354,502 -> 120,298,637 bytes (-5.5%)
//
// So the 52 s buys about 5.5% of module size — almost certainly wasm-ld's
// padded LEBs being re-encoded, since Binaryen itself reports "no passes
// specified, not doing any work". A skipped module is byte-for-byte what
// wasm-ld emitted, which is a valid Wasm 2.0 module and runs; it is just bigger.
// Do not skip it for anything you intend to ship or measure size on.
func (c *LinkAll) finalise(pre string) error {
	if !wasmOptEnabled() {
		// NEUTRALIZATION C: `return copyFile(pre, c.Out)` leaves the pre-module
		// behind and the survival check below catches it.
		//
		// Rename rather than copy: this is a 120 MB+ file and the pre-module has
		// no other consumer.
		return os.Rename(pre, c.Out)
	}
	if err := run("/root/emsdk/upstream/bin/wasm-opt", c.wasmOptArgs(pre)...); err != nil {
		return err
	}
	return os.Remove(pre)
}

func (c *LinkAll) wasmOptArgs(pre string) []string {
	// -O0 by default: wasm-opt's optimiser does not scale to a lifted module.
	// Measured on the linked openssl fixture (123 MB pre-pass):
	//
	//   -O0   30 s      -> 116 MB
	//   -O2   >11 min   -> did not finish, abandoned
	//
	// Raise it with ECV_WASM_OPT_LEVEL for small modules where the size win is
	// worth the time.
	//
	// --translate-to-exnref is GONE. It existed to turn the SjLj shim's legacy EH
	// into the standard proposal; with suspension lowered to a plain return the
	// module needs no EH at all, which is what lets a stock runwasi shim run it.
	//
	// CORRECTION 2026-08-15: this comment used to call the -O0 step "a round-trip
	// that only re-emits the name section". It is not. Binaryen does report "no
	// passes specified, not doing any work", but the module still shrinks 5.5%
	// (127,354,502 -> 120,298,637 on the openssl fixture) because it re-encodes
	// wasm-ld's padded LEBs. Skipping it is therefore a size/time trade, not a
	// free deletion, which is why ECV_WASM_OPT=0 is opt-in — see finalise.
	var args []string

	// -g keeps the wasm NAME SECTION, and it earns its bytes. wasm-ld emits names
	// for every lifted function; wasm-opt drops them without -g, which is why a
	// trap read
	//
	//   calling stack:29, 29, 22751, ..., 14317, 22404, 14317, 22404, ...
	//
	// — bare function indices, unmappable to anything, because the module carried
	// no names. wasmedge prints names when it has them (it already printed
	// "_start").
	//
	// The names are doubly valuable here: elfconv names each lifted function
	// `<sym>_____<idx>_<hexvma>` (lifter/TraceManager.cpp), so ONE name resolves
	// both the guest symbol and its guest VMA. That makes a wasm-level trap
	// directly comparable with ecvisor's own `fn=0x...` diagnostics.
	//
	// Set ECV_WASM_NAMES=0 to strip them for a size-sensitive build.
	if wasmOptNames() {
		args = append(args, "-g")
	}
	return append(args, envOr("ECV_WASM_OPT_LEVEL", "-O0"), pre, "-o", c.Out)
}

func wasmOptNames() bool { return envOr("ECV_WASM_NAMES", "1") != "0" }

// wasmOptEnabled reports whether the wasm-opt finalise step runs at all. See
// finalise for what skipping costs.
func wasmOptEnabled() bool { return envOr("ECV_WASM_OPT", "1") != "0" }
